### ISSUE TITLE
Carts Microservice

### ISSUE THREAD

**Issue by thetsajeet** [Ts-A/Market#4]
### Tasks

- [x] Add to cart
- [x] Remove from cart
- [x] Show cart
- [x] Empty cart
- [x] Create cart when creating a user
- [x] Delete cart when deleting a user
